# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

project_name: anchor

before:
  hooks:
    - go mod tidy

variables:
  windows_product_guid: C5F94F62-E3CC-48E2-AB3C-4DED8C6099E9
  windows_upgrade_code: A7CF6DDC-58DA-4A29-94C7-3D46C9BE0944
  windows_installer_version: 100

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
    id: linux
    goos: [linux]
    goarch: ['amd64','arm64','386']
  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: ['amd64','arm64']
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: ['amd64','386']

archives:
  - id: linux
    builds: [linux]
    format: tar.gz
    <<: &archive_defaults
      wrap_in_directory: true
      name_template: >-
        {{ .ProjectName }}_
        {{- if eq .Os "darwin" }}MacOS
        {{- else}}{{- title .Os }}{{ end }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}
        {{- if .Arm }}v{{ .Arm }}{{ end }}
  - <<: *archive_defaults
    id: macos
    builds: [macos]
    format: zip
  - <<: *archive_defaults
    id: windows
    builds: [windows]
    format: zip

brews:
  - repository:
      name: homebrew-tap
      owner: anchordotdev

    description: Command-line tools for Anchor.dev
    directory: Formula
    homepage: https://anchor.dev/
    license: MIT

    test: |
      assert_match "anchor is a command line interface for the Anchor certificate management platform.", shell_output("#{bin}/anchor")

msi:
- name: msi-builder
  id: anchor-msi
  ids:
    - windows
  wxs: ./windows/app.wxs
  extra_files:
    - ./windows/als2.ico
    - ../../LICENSE
  mod_timestamp: "{{ .CommitTimestamp }}"

chocolateys:
- name: anchor
  ids:
    - anchor-msi
  package_source_url: https://github.com/anchordotdev/cli
  owners: Anchor Security, Inc.
  title: Anchor CLI
  authors: Anchor
  project_url: https://anchor.dev
  use: msi
  url_template: "https://github.com/anchordotdev/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  copyright: 2024 Anchor Security, Inc.
  license_url: https://raw.githubusercontent.com/anchordotdev/cli/main/LICENSE
  require_license_acceptance: false
  project_source_url: https://github.com/anchordotdev/cli
  docs_url: https://anchor.dev/docs
  bug_tracker_url: https://github.com/anchordotdev/cli/issues
  icon_url: https://anchor.dev/images/als2.png
  tags: "security tls ssl certificates localhost https cryptography encryption acme cli x509 X.509"
  summary: "Command-line tools for Anchor.dev"
  description: |
      anchor is a command line interface for the Anchor certificate management platform.
      It provides a developer friendly interface for certificate management.
  release_notes: "https://github.com/anchordotdev/cli/releases/tag/v{{ .Version }}"
  api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
  source_repo: "https://push.chocolatey.org/"
