project_name: anchor

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

brews:
  - repository:
      name: homebrew-tap
      owner: anchordotdev

    description: Command-line tools for Anchor.dev
    folder: Formula
    homepage: https://anchor.dev/
    license: MIT

    test: |
      assert_match "anchor is a command line interface for the Anchor certificate management platform.", shell_output("#{bin}/anchor")
